improve build script
Signed-off-by: kim (grufwub) <grufwub@gmail.com>

diff --git a/build b/build
--- a/build
+++ b/build
@@ -1,3 +1,17 @@
 #!/bin/sh
 
-RUSTFLAGS="-C link-args=-s" cargo build --release
+LOGFILE='build.log'
+
+cargo_build() {
+    RUSTFLAGS="-C link-args=-s" cargo build --release $@ > "$LOGFILE" 2>&1
+}
+
+if [ ! -z "$1" ]; then
+    echo "Building for target "${1}"... (see "${LOGFILE}" for output)"
+    cargo_build --target="$1"
+else
+    echo "Building for default target... (see "${LOGFILE}" for output)"
+    cargo_build
+fi
+
+[ $? -ne 0 ] && echo 'BUILD FAILED!'
